USE OSCAR_DATABASE;
-- EXERCICIO 1 --
SELECT COUNT(*) FROM FILMES WHERE NOME_DO_INDICADO = "NATALIE PORTMAN";

-- EXERCICIO 2 --
SELECT COUNT(*) FROM FILMES WHERE NOME_DO_INDICADO = "NATALIE PORTMAN" AND VENCEDOR = "SIM";

-- EXERCICIO 3 --
SELECT COUNT(*) FROM FILMES WHERE NOME_DO_INDICADO = "AMY ADAMS" AND VENCEDOR = "SIM";

-- EXERCICIO 4 --
SELECT ANO_FILMAGEM FROM FILMES WHERE NOME_FILME LIKE "%TOY STORY%" AND VENCEDOR = "SIM";

-- EXERCICIO 5 --
SELECT MAX(ANO_CERIMONIA) FROM FILMES WHERE CATEGORIA = "ACTRESS";

-- EXERCICIO 6 --
SELECT MIN(ANO_CERIMONIA) FROM FILMES WHERE CATEGORIA = "ACTRESS";
SELECT NOME_DO_INDICADO FROM FILMES WHERE CATEGORIA = "ACTRESS" AND ANO_CERIMONIA = "1928";

-- EXERCICIO 7 --
UPDATE FILMES SET VENCEDOR = "0" WHERE VENCEDOR = "NÃO";
UPDATE FILMES SET VENCEDOR = "1" WHERE VENCEDOR = "SIM";

-- EXERCICIO 8 --
SELECT ANO_CERIMONIA FROM FILMES WHERE NOME_FILME = "CRASH";

-- EXERCICIO 9 --
SELECT NOME_FILME, VENCEDOR, CATEGORIA FROM FILMES WHERE NOME_FILME LIKE "WHIPLASH";

-- EXERCICIO 10 --
SELECT NOME_FILME FROM FILMES WHERE NOME_FILME = "CENTRAL DO BRASIL";

-- EXERCICIO 11 --
#SELECT

-- EXERCICIO 12 --
SELECT NOME_FILME FROM FILMES WHERE ANO_CERIMONIA = "2004" AND VENCEDOR = "1";
SELECT NOME_FILME, NOME_DO_INDICADO, CATEGORIA FROM FILMES WHERE
	ANO_CERIMONIA = "2004" AND CATEGORIA LIKE "%DIRECTING%" AND VENCEDOR = "1";
SELECT NOME_FILME, NOME_DO_INDICADO, CATEGORIA FROM FILMES WHERE
	ANO_CERIMONIA = "2004" AND CATEGORIA LIKE "%ACTRESS%" AND VENCEDOR = "1";
